const navLinks = [
  { name: "Home", path: "/homeGrocery" },
  { name: "Fashion", path: "/homeFashion" },
  { name: "Fashion 2", path: "/homeFashion2" },
  { name: "Sidebar", path: "/leftSidebar" },
  { name: "PL Sidebar", path: "/plsidebar" },
  { name: "Checkout", path: "/checkout" },
  { name: "Wishlist", path: "/wishlist" },
  { name: "Product", path: "/productFull" },
  { name: "Blog", path: "/blog" },
  { name: "Blog Details", path: "/blogDetails" },
  { name: "About", path: "/aboutUs" },
  { name: "Cart", path: "/cart" },
  { name: "Orders", path: "/orders" },
  { name: "Compare", path: "/compare" },
  { name: "FAQ", path: "/faq" },
  { name: "Login", path: "/login" },
];
